### ISSUE TITLE
Can this be used with notify-command?

### ISSUE THREAD

**Issue by sir-pinecone** [mike-thompson-day8/cljsbuild-none-test-seed#2]
I want the tests to auto-run after they are compiled. I see in clojurescript.test that this can be done using `:notify-command` in the cljsbuild config. 

I haven't had much luck getting it to work with your setup. I removed `:test-commands` and added in:

> :notify-command ["phantomjs" "test/bin/runner-none.js" "compiled/test" "compiled/test.js"]

Then I ran `lein cljsbuild auto test` and saved a file. Results in the error: 

> ERROR: SyntaxError: Parse error
> STACK TRACE:
> Possible cause: the namespace cemerick.cljs.test isn't defined.
> To resolve: ensure [cemerick.cljs.test] appears in the :require clause of your test suite. Also, ensure there's one or more test files.

Any ideas? 

p.s. I kinda don't mind using the test.html approach with figwheel if the above stuff is not possible. But I'm not sure how I would get the test page to refresh after my code compiles. I'm a noob! :]

**Comment by pjagielski** [comment]
The problem is in this part of `runner-none.js`:
```javascript
for (var i = 3; i < system.args.length; i++) {
    var arg = system.args[i];
    if (fs.exists(arg)) {
        if (!page.injectJs(arg))
          throw new Error("Failed to inject " + arg);
     } else {
         page.evaluateJavaScript("(function () { " + arg + ";" + " })");
    }
}
```
The `notify-command` hook passes "Successfully compiled "compiled/test.js" in 0.177 seconds." as last arg of phantomjs invocation and runner-none.js treats is as a valid javascript code.

Uncommenting the `else` branch from the code above worked for me.
